import { supabase } from "../lib/supabase";
export const ATTACHMENT_BUCKET="household-attachments";
export const MAX_ATTACHMENT_BYTES=10*1024*1024;
export const ALLOWED_ATTACHMENT_TYPES=["image/jpeg","image/png","image/webp","application/pdf"];
export function validateAttachment(file){if(!file)return "Choose a file.";if(!ALLOWED_ATTACHMENT_TYPES.includes(file.type))return "Use a JPEG, PNG, WebP, or PDF file.";if(file.size>MAX_ATTACHMENT_BYTES)return "Files must be 10 MB or smaller.";return "";}
export function safeStorageName(name){const ext=String(name||"").split(".").pop().toLowerCase().replace(/[^a-z0-9]/g,"").slice(0,8);const id=(typeof window!=="undefined"&&window.crypto?.randomUUID?.())||`${Date.now().toString(16)}-${Math.random().toString(16).slice(2)}`;return `${id}${ext?`.${ext}`:""}`;}
export async function uploadAttachment({file,householdId,entityType,entityId,category="other",onProgress}){const error=validateAttachment(file);if(error)throw new Error(error);const path=`households/${householdId}/${entityType}/${entityId}/${safeStorageName(file.name)}`;onProgress?.(20);const uploaded=await supabase.storage.from(ATTACHMENT_BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;onProgress?.(75);const metadata=await supabase.from("attachments").insert({household_id:householdId,entity_type:entityType,entity_id:entityId,storage_bucket:ATTACHMENT_BUCKET,storage_path:path,original_filename:file.name,display_name:file.name,mime_type:file.type,size_bytes:file.size,category}).select().single();if(metadata.error){await supabase.storage.from(ATTACHMENT_BUCKET).remove([path]);throw metadata.error;}onProgress?.(100);return metadata.data;}
export async function signedAttachmentUrl(attachment,expiresIn=300){const result=await supabase.storage.from(attachment.storage_bucket).createSignedUrl(attachment.storage_path,expiresIn);if(result.error)throw result.error;return result.data.signedUrl;}
export async function deleteAttachment(attachment){const removed=await supabase.storage.from(attachment.storage_bucket).remove([attachment.storage_path]);if(removed.error)throw removed.error;const metadata=await supabase.from("attachments").delete().eq("id",attachment.id);if(metadata.error)throw metadata.error;}
