const { test, expect } = require("@playwright/test");
const { assertNoRuntimeFailures, loginDemoUser, monitorPage, navigateModule, openMoreModule } = require("./helpers/app");

test("authenticated FamilyOS major-module smoke", async ({ page }, testInfo) => {
  const failures = monitorPage(page);
  await loginDemoUser(page);
  await expect(page.getByRole("navigation", { name: "Primary navigation" })).toBeVisible();
  await expect(page.getByRole("main", { name: "Today dashboard" })).toBeVisible();
  const primary=page.getByRole("navigation",{name:"Primary navigation"});
  await expect(primary.getByRole("button")).toHaveText(["Home","Habits","Calendar","Tasks","More"]);
  await expect(page.getByRole("button", { name: "Add household item" })).toBeVisible();
  await expect(primary.getByRole("button",{name:"Pool"})).toHaveCount(0);
  await expect(primary.getByRole("button",{name:"Attention"})).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Add household item" })).toBeVisible();
  await expect(primary.getByRole("button", { name: "Quick Add" })).toHaveCount(0);
  await page.getByRole("button", { name: "Add household item" }).click();
  await page.getByLabel("Describe one household item").fill("Replace HVAC filter next month");
  await page.getByRole("button", { name: "Review detected item" }).click();
  await expect(page.getByText(/maintenance · Replace HVAC filter/i)).toBeVisible();
  await expect(page.getByText(/Resolved date:/)).toBeVisible();
  await page.getByRole("button", { name: "Cancel" }).click();
  await expect(page.getByRole("button", { name: "Open Calendar" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Tasks" })).toBeVisible();
  await expect(page.getByText(/family brief/i, { exact: true })).toBeVisible();
  await expect(page.getByText(/Schedule annual physical/).first()).toBeVisible();

  await page.keyboard.press("Control+K");
  await expect(page.getByText("Search Family OS", { exact: true })).toBeVisible();
  await page.getByPlaceholder("Search tasks, pool, lists, meals...").fill("annual physical");
  await expect(page.getByText("Schedule annual physical", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Close" }).last().click();

  await page.getByRole("button", { name: "Open Tasks" }).click();
  await expect(page.getByRole("button", { name: "My Tasks", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Overdue", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Upcoming", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "More Filters" }).click();
  await expect(page.getByRole("button", { name: "Today", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "This Week", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: /Select visible/i })).toHaveCount(0);
  await expect(page.getByText("Schedule annual physical")).toBeVisible();
  await navigateModule(page, "Home");
  await page.getByRole("button", { name: "Open Calendar" }).click();
  await expect(page.getByText("Calendar", { exact: true }).first()).toBeVisible();
  await navigateModule(page, "Home");
  await expect(page.getByText("FamilyOS", { exact: false }).first()).toBeVisible();

  await navigateModule(page,"Habits");
  await expect(page.getByText("Morning checklist",{exact:true})).toBeVisible();
  const checklistSummary=page.getByText("Morning checklist",{exact:true}).locator("..");
  await expect(checklistSummary).toBeVisible();
  await page.getByRole("button",{name:"Expand Morning checklist"}).click();
  await expect(page.getByRole("checkbox",{name:"Take vitamins"})).toBeVisible();
  const vitamins=page.getByRole("checkbox",{name:"Take vitamins"}),before=await vitamins.getAttribute("aria-checked");
  await vitamins.click();
  await expect(vitamins).toHaveAttribute("aria-checked",before==="true"?"false":"true");
  await page.getByRole("button",{name:/Add action/}).first().click();
  await page.getByLabel("New action for Morning checklist").fill(`Smoke ${testInfo.project.name}`);
  await page.getByRole("main").getByRole("button",{name:"Add",exact:true}).click();
  await expect(page.getByText(`Smoke ${testInfo.project.name}`,{exact:true}).first()).toBeVisible();
  await checklistSummary.click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button",{name:"Close"}).click();
  await expect(page.getByText("Evening routine",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Expand Evening routine"}).click();
  await expect(page.getByRole("checkbox",{name:"Prepare coffee"})).toBeVisible();

  await openMoreModule(page, "Life Lists");
  await expect(page.getByText("Family Goals").first()).toBeVisible();
  await openMoreModule(page, "Pool");
  await expect(page.getByText("Pool", { exact: true }).first()).toBeVisible();
  const recommendation=page.getByRole("button",{name:/Recommended Next Step/});
  await expect(recommendation).toHaveAttribute("aria-expanded","false");
  await recommendation.click();
  await expect(page.getByText("Current condition",{exact:true})).toBeVisible();
  await openMoreModule(page, "Home Operations");
  await expect(page.getByRole("heading", { name: "Assets & Maintenance" })).toBeVisible();
  await openMoreModule(page, "Household Timeline");
  await expect(page.getByRole("main", { name: "Household Timeline" })).toBeVisible();
  await expect(page.getByText(/Shopping is intentionally excluded/)).toBeVisible();
  await navigateModule(page,"More");
  await expect(page.getByRole("button", { name: /^Shopping/ })).toHaveCount(0);
  await openMoreModule(page, "AI Workspace");
  await expect(page.getByRole("heading", { name: "Ask FamilyOS" })).toBeVisible();
  await page.getByRole("button", { name: /Full generated prompt/ }).click();
  await expect(page.getByLabel("Generated FamilyOS prompt")).toBeVisible();
  await expect(page.getByRole("button", { name: "Copy Prompt" })).toBeEnabled();
  await expect(page.getByLabel("AI response to review")).toBeVisible();
  await page.getByLabel("AI response to review").fill("Task: Schedule follow-up 2026-07-20\nCalendar: Dentist 2026-07-21\nPool: Retest chlorine\nLife List: Visit Maine\nFinance: Review contribution rate");
  await expect(page.getByRole("button", { name: "Review prefilled form" })).toHaveCount(4);
  await expect(page.getByRole("link", { name: "Review in Calendar" })).toHaveAttribute("href", /calendar\.google\.com/);
  await openMoreModule(page, "Meal Planning");
  await openMoreModule(page, "Finance");
  await expect(page.getByText("Monthly Contributions", { exact: true })).toBeVisible();
  await openMoreModule(page, "College");

  assertNoRuntimeFailures(failures);
});
