import { useMemo } from "react";
import { CheckCircle2, Clock3, Copy, RotateCcw } from "lucide-react";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { Checkbox } from "../../components/ui/checkbox";
import { EmptyStatePanel } from "../../components/ui/empty-state";
import { SectionHeader } from "../../components/ui/section-header";
import { useTable } from "../../hooks/useTable";
import { S } from "../../theme";
import { requiredStepsComplete, routinePeriodKey, toggleCompletedStep } from "./routineStore";

export function Routines() {
  const routines=useTable("routines","created_at",true),steps=useTable("routine_steps","sort_order",true,{userId:null}),completions=useTable("routine_completions","created_at");
  const active=useMemo(()=>routines.data.filter(r=>!r.archived),[routines.data]);
  async function toggle(routine,step){const period=routinePeriodKey(routine);const current=completions.data.find(c=>c.routine_id===routine.id&&c.period_key===period);const ids=toggleCompletedStep(current?.completed_step_ids||[],step.id);const routineSteps=steps.data.filter(s=>s.routine_id===routine.id);const row={routine_id:routine.id,period_key:period,completed_step_ids:ids,completed_at:requiredStepsComplete(routineSteps,ids)?new Date().toISOString():null};if(current)await completions.update(current.id,row);else await completions.insert(row);}
  async function complete(routine){const period=routinePeriodKey(routine);const current=completions.data.find(c=>c.routine_id===routine.id&&c.period_key===period);const ids=steps.data.filter(s=>s.routine_id===routine.id).map(s=>s.id);const row={routine_id:routine.id,period_key:period,completed_step_ids:ids,completed_at:new Date().toISOString()};if(current)await completions.update(current.id,row);else await completions.insert(row);}
  async function duplicate(routine){const copy=await routines.insert({name:`${routine.name} copy`,description:routine.description||"",estimated_minutes:routine.estimated_minutes,recurrence:routine.recurrence,visibility:routine.visibility||"household",archived:false});const list=steps.data.filter(s=>s.routine_id===routine.id).sort((a,b)=>a.sort_order-b.sort_order);for(const step of list)await steps.insert({routine_id:copy.id,title:step.title,optional:step.optional,sort_order:step.sort_order});}
  async function cycleRecurrence(routine){const order=["once","daily","weekly"];await routines.update(routine.id,{...routine,recurrence:order[(order.indexOf(routine.recurrence)+1)%order.length]});}
  return <main style={S.screen} className="space-y-4"><div><h1 className="text-xl font-extrabold">Routines</h1><p className="text-sm text-muted-foreground">Repeat dependable household checklists without losing history.</p></div><Card><CardContent className="p-3 text-xs text-muted-foreground"><b className="text-foreground">Templates:</b> use Add Routine for Morning reset, School night, Travel packing, or Weekly home reset, then duplicate and tailor the checklist.</CardContent></Card><SectionHeader title="Active routines" count={active.length} tone="blue"/>{!active.length?<Card><EmptyStatePanel title="No routines yet" detail="Use Add Routine to create an ordered daily, weekly, or one-time checklist."/></Card>:active.map(r=>{const period=routinePeriodKey(r);const completion=completions.data.find(c=>c.routine_id===r.id&&c.period_key===period);const done=Boolean(completion?.completed_at);const list=steps.data.filter(s=>s.routine_id===r.id).sort((a,b)=>a.sort_order-b.sort_order);const completedIds=completion?.completed_step_ids||[],required=list.filter(s=>!s.optional),progress=required.length?Math.round(required.filter(s=>completedIds.includes(s.id)).length/required.length*100):0,history=completions.data.filter(c=>c.routine_id===r.id&&c.completed_at).length;return <Card key={r.id}><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-bold">{r.name}</div><div className="mt-1 flex flex-wrap gap-3 text-xs text-muted-foreground"><button type="button" onClick={()=>cycleRecurrence(r)} className="capitalize underline">{r.recurrence} · edit</button>{r.estimated_minutes&&<span className="flex items-center gap-1"><Clock3 className="h-3 w-3"/>{r.estimated_minutes} min</span>}<span>{history} completed run{history===1?"":"s"}</span></div></div><div className="flex gap-1"><Button size="icon-xs" variant="ghost" aria-label={`Duplicate ${r.name}`} onClick={()=>duplicate(r)}><Copy className="h-4 w-4"/></Button>{done?<span className="flex items-center gap-1 text-xs font-bold text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Complete</span>:<Button size="xs" onClick={()=>complete(r)}>Complete all</Button>}</div></div><div><div className="mb-1 flex justify-between text-xs"><span>Progress</span><b>{progress}%</b></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${progress}%`}}/></div></div>{list.map(step=><label key={step.id} className="flex min-h-11 items-center gap-3 border-t border-border pt-2"><Checkbox checked={completedIds.includes(step.id)} onCheckedChange={()=>toggle(r,step)}/><span className="flex-1 text-sm">{step.title}</span>{step.optional&&<span className="text-xs text-muted-foreground">Optional</span>}</label>)}{done&&<div className="flex items-center gap-1 text-xs text-muted-foreground"><RotateCcw className="h-3 w-3"/>Resets automatically in the next {r.recurrence} period.</div>}</CardContent></Card>})}</main>;
}
