import { useMemo, useState } from "react";
import { CheckCircle2, Clock3, Copy, Library, RotateCcw } from "lucide-react";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { Checkbox } from "../../components/ui/checkbox";
import { EmptyStatePanel } from "../../components/ui/empty-state";
import { SectionHeader } from "../../components/ui/section-header";
import { useTable } from "../../hooks/useTable";
import { S } from "../../theme";
import { requiredStepsComplete, routinePeriodKey, toggleCompletedStep } from "./routineStore";
import { BUILT_IN_TEMPLATES, templateToRoutine } from "./templateLibrary";

export function Routines() {
  const routines=useTable("routines","created_at",true),steps=useTable("routine_steps","sort_order",true,{userId:null}),completions=useTable("routine_completions","created_at");
  const templates=useTable("routine_templates","created_at",true),templateSteps=useTable("routine_template_steps","sort_order",true,{userId:null});
  const [showTemplates,setShowTemplates]=useState(false),[preview,setPreview]=useState(null),[message,setMessage]=useState("");
  const active=useMemo(()=>routines.data.filter(r=>!r.archived),[routines.data]);
  const customTemplates=useMemo(()=>templates.data.filter(t=>!t.archived).map(t=>({...t,title:t.title,recurrence:t.recurrence_guidance,steps:templateSteps.data.filter(s=>s.template_id===t.id).sort((a,b)=>a.sort_order-b.sort_order).map(s=>s.title)})),[templateSteps.data,templates.data]);
  const library=[...BUILT_IN_TEMPLATES,...customTemplates];
  async function toggle(routine,step){const period=routinePeriodKey(routine);const current=completions.data.find(c=>c.routine_id===routine.id&&c.period_key===period);const ids=toggleCompletedStep(current?.completed_step_ids||[],step.id);const routineSteps=steps.data.filter(s=>s.routine_id===routine.id);const row={routine_id:routine.id,period_key:period,completed_step_ids:ids,completed_at:requiredStepsComplete(routineSteps,ids)?new Date().toISOString():null};if(current)await completions.update(current.id,row);else await completions.insert(row);}
  async function complete(routine){const period=routinePeriodKey(routine);const current=completions.data.find(c=>c.routine_id===routine.id&&c.period_key===period);const ids=steps.data.filter(s=>s.routine_id===routine.id).map(s=>s.id);const row={routine_id:routine.id,period_key:period,completed_step_ids:ids,completed_at:new Date().toISOString()};if(current)await completions.update(current.id,row);else await completions.insert(row);}
  async function createFromTemplate(template){const copy=await routines.insert(templateToRoutine(template));for(const [index,title] of (template.steps||[]).entries())await steps.insert({routine_id:copy.id,title,optional:false,sort_order:index});setMessage(`${template.title} created. Customize it in Routines.`);setPreview(null);setShowTemplates(false);}
  async function duplicate(routine){const copy=await routines.insert({name:`${routine.name} copy`,description:routine.description||"",estimated_minutes:routine.estimated_minutes,recurrence:routine.recurrence,visibility:routine.visibility||"household",archived:false});const list=steps.data.filter(s=>s.routine_id===routine.id).sort((a,b)=>a.sort_order-b.sort_order);for(const step of list)await steps.insert({routine_id:copy.id,title:step.title,optional:step.optional,sort_order:step.sort_order});}
  async function saveAsTemplate(routine){const template=await templates.insert({title:routine.name,description:routine.description||"",estimated_minutes:routine.estimated_minutes,recurrence_guidance:routine.recurrence,built_in:false,archived:false});const list=steps.data.filter(s=>s.routine_id===routine.id).sort((a,b)=>a.sort_order-b.sort_order);for(const step of list)await templateSteps.insert({template_id:template.id,title:step.title,optional:step.optional,sort_order:step.sort_order});setMessage(`${routine.name} saved as a reusable template.`);}
  async function duplicateTemplate(template){const created=await templates.insert({title:`${template.title} copy`,description:template.description||"",estimated_minutes:template.estimated_minutes,recurrence_guidance:template.recurrence||"once",built_in:false,archived:false});for(const [index,title] of (template.steps||[]).entries())await templateSteps.insert({template_id:created.id,title,optional:false,sort_order:index});}
  async function archiveTemplate(template){if(template.built_in)return;await templates.update(template.id,{archived:true});setPreview(null);}
  async function renameTemplate(template){if(template.built_in)return;await templates.update(template.id,{title:template.title.endsWith(" updated")?template.title.replace(/ updated$/,""): `${template.title} updated`});}
  async function cycleRecurrence(routine){const order=["once","daily","weekly"];await routines.update(routine.id,{...routine,recurrence:order[(order.indexOf(routine.recurrence)+1)%order.length]});}
  return <main style={S.screen} className="space-y-4"><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-extrabold">Routines</h1><p className="text-sm text-muted-foreground">Repeat dependable household checklists without losing history.</p></div><Button type="button" size="xs" variant="secondary" onClick={()=>setShowTemplates(v=>!v)}><Library className="h-4 w-4"/>Templates</Button></div>{message&&<div role="status" className="rounded-lg border border-emerald-700 bg-emerald-950/30 p-3 text-sm">{message}</div>}
  {showTemplates&&<section aria-labelledby="routine-template-heading"><SectionHeader title="Routine Templates" count={library.length} tone="purple"/><p id="routine-template-heading" className="mb-3 text-xs text-muted-foreground">Preview and copy a template. Existing routines never change when a template is edited.</p><div className="grid gap-2 sm:grid-cols-2">{library.map(template=><Card key={template.template_key||template.id}><CardContent className="space-y-2 p-3"><div className="flex justify-between gap-2"><div><div className="font-bold">{template.title}</div><div className="text-xs text-muted-foreground">{template.built_in?"Built-in · protected":"Household template"} · {template.estimated_minutes||"Flexible"} min</div></div><Button size="xs" variant="secondary" onClick={()=>setPreview(template)}>Preview</Button></div><p className="text-xs leading-5 text-muted-foreground">{template.description}</p>{!template.built_in&&<div className="flex flex-wrap gap-1"><Button size="xs" variant="ghost" onClick={()=>renameTemplate(template)}>Edit title</Button><Button size="xs" variant="ghost" onClick={()=>duplicateTemplate(template)}>Duplicate</Button><Button size="xs" variant="destructive-outline" onClick={()=>archiveTemplate(template)}>Archive</Button></div>}</CardContent></Card>)}</div>{preview&&<Card className="mt-3 border-primary"><CardContent className="space-y-3 p-4"><div><div className="font-bold">{preview.title}</div><div className="text-xs text-muted-foreground">{preview.recurrence||preview.recurrence_guidance} guidance</div></div><ol className="list-decimal space-y-1 pl-5 text-sm">{(preview.steps||[]).map((step,index)=><li key={`${step}-${index}`}>{step}</li>)}</ol><div className="flex gap-2"><Button size="xs" onClick={()=>createFromTemplate(preview)}>Create routine</Button><Button size="xs" variant="secondary" onClick={()=>setPreview(null)}>Close preview</Button></div></CardContent></Card>}</section>}
  <SectionHeader title="Active routines" count={active.length} tone="blue"/>{!active.length?<Card><EmptyStatePanel title="No routines yet" detail="Open Templates to create a useful checklist." action="Browse templates" onAction={()=>setShowTemplates(true)}/></Card>:active.map(r=>{const period=routinePeriodKey(r);const completion=completions.data.find(c=>c.routine_id===r.id&&c.period_key===period);const done=Boolean(completion?.completed_at);const list=steps.data.filter(s=>s.routine_id===r.id).sort((a,b)=>a.sort_order-b.sort_order);const completedIds=completion?.completed_step_ids||[],required=list.filter(s=>!s.optional),progress=required.length?Math.round(required.filter(s=>completedIds.includes(s.id)).length/required.length*100):0,history=completions.data.filter(c=>c.routine_id===r.id&&c.completed_at).length;return <Card key={r.id}><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-bold">{r.name}</div><div className="mt-1 flex flex-wrap gap-3 text-xs text-muted-foreground"><button type="button" onClick={()=>cycleRecurrence(r)} className="capitalize underline">{r.recurrence} · edit</button>{r.estimated_minutes&&<span className="flex items-center gap-1"><Clock3 className="h-3 w-3" aria-hidden="true"/>{r.estimated_minutes} min</span>}<span>{history} completed run{history===1?"":"s"}</span></div></div><div className="flex flex-wrap justify-end gap-1"><Button size="icon-xs" variant="ghost" aria-label={`Save ${r.name} as template`} onClick={()=>saveAsTemplate(r)}><Library className="h-4 w-4"/></Button><Button size="icon-xs" variant="ghost" aria-label={`Duplicate ${r.name}`} onClick={()=>duplicate(r)}><Copy className="h-4 w-4"/></Button>{done?<span className="flex items-center gap-1 text-xs font-bold text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Complete</span>:<Button size="xs" onClick={()=>complete(r)}>Complete all</Button>}</div></div><div><div className="mb-1 flex justify-between text-xs"><span>Progress</span><b>{progress}%</b></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${progress}%`}}/></div></div>{list.map(step=><label key={step.id} className="flex min-h-11 items-center gap-3 border-t border-border pt-2"><Checkbox checked={completedIds.includes(step.id)} onCheckedChange={()=>toggle(r,step)}/><span className="flex-1 text-sm">{step.title}</span>{step.optional&&<span className="text-xs text-muted-foreground">Optional</span>}</label>)}{done&&<div className="flex items-center gap-1 text-xs text-muted-foreground"><RotateCcw className="h-3 w-3"/>Resets automatically in the next {r.recurrence} period.</div>}</CardContent></Card>})}</main>;
}
