import{useMemo,useState}from"react";import{Bot,Check,Clipboard,Eye,ShieldCheck}from"lucide-react";
import{Button}from"../../components/ui/button";import{Card,CardContent}from"../../components/ui/card";import{Input}from"../../components/ui/input";import{SectionHeader}from"../../components/ui/section-header";import{useTable}from"../../hooks/useTable";import{useHousehold}from"../../context/HouseholdContext";
import{buildContextEngine,calendarContext,financialContext,homeContext,lifeContext,poolContext,taskContext}from"../../services/contextEngine";import{buildPrompt}from"../../services/promptBuilder";import{readAiSettings,readPromptTraces,recordPromptTrace}from"../../services/aiPreferences";import{buildPoolContext}from"../pool/domainService";import{identifySuggestions}from"./responseReview";import{S}from"../../theme";
const QUESTIONS=["What needs attention this week?","Summarize my family's schedule.","Prepare my weekend.","What should I accomplish today?","Review my pool.","Summarize upcoming expenses."];
export function AIWorkspace({calendarEvents=[]}){const household=useHousehold();const tasks=useTable("tasks","due_date",true),lists=useTable("life_lists","updated_at"),items=useTable("life_list_items","updated_at"),readings=useTable("pool_readings","logged_at"),treatments=useTable("pool_treatments","logged_at"),profiles=useTable("pool_profiles","name",true),equipment=useTable("pool_equipment","type",true),maintenance=useTable("home_maintenance","last_completed"),accounts=useTable("retirement_accounts","name",true),assumptions=useTable("retirement_assumptions","id",true);const settings=readAiSettings();const[question,setQuestion]=useState(QUESTIONS[0]);const[copied,setCopied]=useState(false);const[response,setResponse]=useState("");const[accepted,setAccepted]=useState([]);const[traces,setTraces]=useState(readPromptTraces());
  const context=useMemo(()=>{const pool=buildPoolContext({householdIdentifier:household.householdId,profile:profiles.data[0],readings:readings.data,treatments:treatments.data,equipment:equipment.data});return buildContextEngine([taskContext(tasks.data),calendarContext(calendarEvents),lifeContext(lists.data,items.data),poolContext(pool),homeContext(maintenance.data),financialContext(accounts.data,assumptions.data)],{role:household.membership?.role,financialContextAllowed:!settings.hideSensitiveFinancialData,childContextAllowed:!settings.hideChildInformation,timezone:household.householdSettings?.timezone});},[accounts.data,assumptions.data,calendarEvents,equipment.data,household.householdId,household.householdSettings?.timezone,household.membership?.role,items.data,lists.data,maintenance.data,profiles.data,readings.data,settings.hideChildInformation,settings.hideSensitiveFinancialData,tasks.data,treatments.data]);
  const result=useMemo(()=>buildPrompt(context,question,settings),[context,question,settings]);const suggestions=useMemo(()=>identifySuggestions(response),[response]);if(!settings.enabled)return<div style={S.screen}><Card><CardContent className="p-5 text-sm text-muted-foreground">AI Workspace is disabled in Settings.</CardContent></Card></div>;
  async function copy(){await navigator.clipboard.writeText(result.prompt);recordPromptTrace(result.preview,question);setTraces(readPromptTraces());setCopied(true);setTimeout(()=>setCopied(false),2000);}
  return <div style={S.screen} className="space-y-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-muted-foreground"><Bot className="h-4 w-4"/>AI Workspace</div><h1 className="mt-1 text-2xl font-extrabold">Ask FamilyOS</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">FamilyOS prepares context for your review. Nothing is transmitted and no AI output can change records automatically.</p></div><Card><CardContent className="space-y-3 p-4"><label htmlFor="ai-question" className="text-sm font-bold">Question</label><Input id="ai-question" value={question} onChange={e=>setQuestion(e.target.value)}/><div className="flex flex-wrap gap-2">{QUESTIONS.map(item=><Button key={item} type="button" size="xs" variant="secondary" onClick={()=>setQuestion(item)}>{item}</Button>)}</div></CardContent></Card>
  {settings.promptPreview&&<Card><CardContent className="space-y-3 p-4"><SectionHeader title="Prompt Preview" tone="purple"/><div className="grid grid-cols-2 gap-2 text-xs"><div><b>Included modules</b><div>{result.preview.includedModules.join(", ")||"None"}</div></div><div><b>Estimated size</b><div>~{result.preview.estimatedTokens} tokens</div></div><div><b>Prompt version</b><div>{result.preview.promptVersion}</div></div><div><b>Excluded sections</b><div>{result.preview.excludedSections.length||"None"}</div></div></div><div className="flex items-start gap-2 rounded-lg border border-border bg-secondary p-3 text-xs leading-5"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary"/><span>{result.preview.privacyNotes.join(" · ")}</span></div><textarea readOnly value={result.prompt} aria-label="Generated FamilyOS prompt" className="min-h-72 w-full rounded-md border border-border bg-secondary p-3 text-xs leading-5"/><Button type="button" className="w-full" onClick={copy}>{copied?<Check/>:<Clipboard/>}{copied?"Copied":"Copy Prompt"}</Button></CardContent></Card>}
  <Card><CardContent className="space-y-3 p-4"><SectionHeader title="AI Response Review" tone="neutral"/><p className="text-xs leading-5 text-muted-foreground">Optional: paste an AI response. FamilyOS identifies possible records, but nothing is imported automatically.</p><textarea value={response} onChange={e=>setResponse(e.target.value)} aria-label="AI response to review" placeholder="Paste AI output here" className="min-h-36 w-full rounded-md border border-border bg-secondary p-3 text-sm"/>{suggestions.map(item=><div key={item.id} className="flex items-start gap-3 rounded-lg border border-border p-3"><Eye className="mt-1 h-4 w-4 text-primary"/><div className="min-w-0 flex-1"><div className="text-xs font-bold text-muted-foreground">{item.label}</div><div className="text-sm">{item.text}</div></div><Button size="xs" variant={accepted.includes(item.id)?"default":"secondary"} onClick={()=>setAccepted(x=>x.includes(item.id)?x:[...x,item.id])}>{accepted.includes(item.id)?"Accepted for manual entry":"Review and accept"}</Button></div>)}</CardContent></Card>
  <Card><CardContent className="p-4"><SectionHeader title="Recent Prompts" count={traces.length} tone="neutral"/>{traces.length?traces.map(item=><div key={item.timestamp} className="border-b border-border py-2 text-xs last:border-0"><div className="font-semibold">{item.question}</div><div className="text-muted-foreground">{new Date(item.timestamp).toLocaleString()} · {item.modulesIncluded.join(", ")} · ~{item.estimatedTokenCount} tokens</div></div>):<p className="text-sm text-muted-foreground">No prompts copied on this device.</p>}</CardContent></Card></div>;
}
