import { useMemo, useState } from "react";
import { Bot, Check, Clipboard, ExternalLink, Eye, Heart, ShieldCheck } from "lucide-react";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { SectionHeader } from "../../components/ui/section-header";
import { ExpandableSection } from "../../components/ui/expandable-section";
import { useTable } from "../../hooks/useTable";
import { useHousehold } from "../../context/HouseholdContext";
import { buildContextEngine, calendarContext, financialContext, habitContext, homeContext, lifeContext, poolContext, routineContext, taskContext } from "../../services/contextEngine";
import { buildPrompt } from "../../services/promptBuilder";
import { readAiSettings, readPromptTraces, recordPromptTrace, writeAiSettings } from "../../services/aiPreferences";
import { buildPoolContext } from "../pool/domainService";
import { identifySuggestions } from "./responseReview";
import { googleCalendarUrl, workflowNavigation } from "./guidedWorkflows";
import { S } from "../../theme";
import { BriefScheduler } from "./BriefScheduler";

const QUESTIONS = ["Morning Brief: summarize today's priorities, calendar, habits, pool, and household reminders.", "Evening Review: summarize completed work, remaining work, missed habits, and tomorrow preparation.", "Weekly Planning: summarize deadlines, family events, pool history-based recommendations, habit trends, and suggested priorities.", "What needs attention this week?", "Prepare my weekend.", "Review my pool."];

export function AIWorkspace({ calendarEvents = [], onNavigate, initialView }) {
  const household = useHousehold();
  const tasks = useTable("tasks", "due_date", true), lists = useTable("life_lists", "updated_at"), items = useTable("life_list_items", "updated_at"), readings = useTable("pool_readings", "logged_at"), treatments = useTable("pool_treatments", "logged_at"), profiles = useTable("pool_profiles", "name", true), equipment = useTable("pool_equipment", "type", true), maintenance = useTable("home_maintenance", "last_completed"), accounts = useTable("retirement_accounts", "name", true), assumptions = useTable("retirement_assumptions", "id", true),habits=useTable("habits","created_at",true),habitCompletions=useTable("habit_completions","completed_at"),routines=useTable("routines","created_at",true),routineCompletions=useTable("routine_completions","created_at");
  const [settings, setSettings] = useState(readAiSettings);
  const [question, setQuestion] = useState(() => readAiSettings().defaultPromptTemplate || QUESTIONS[0]);
  const [copied, setCopied] = useState(false), [response, setResponse] = useState(""), [traces, setTraces] = useState(readPromptTraces());
  const context = useMemo(() => {
    const pool = buildPoolContext({ householdIdentifier: household.householdId, profile: profiles.data[0], readings: readings.data, treatments: treatments.data, equipment: equipment.data });
    return buildContextEngine([taskContext(tasks.data), calendarContext(calendarEvents),habitContext(habits.data,habitCompletions.data),routineContext(routines.data,routineCompletions.data), lifeContext(lists.data, items.data), poolContext(pool), homeContext(maintenance.data), financialContext(accounts.data, assumptions.data)], { role: household.membership?.role, financialContextAllowed: !settings.hideSensitiveFinancialData, childContextAllowed: !settings.hideChildInformation, timezone: household.householdSettings?.timezone });
  }, [accounts.data, assumptions.data, calendarEvents, equipment.data,habitCompletions.data,habits.data, household.householdId, household.householdSettings?.timezone, household.membership?.role, items.data, lists.data, maintenance.data, profiles.data, readings.data,routineCompletions.data,routines.data, settings.hideChildInformation, settings.hideSensitiveFinancialData, tasks.data, treatments.data]);
  const result = useMemo(() => buildPrompt(context, question, settings), [context, question, settings]);
  const scheduledPrompts = useMemo(()=>Object.fromEntries([["morning",QUESTIONS[0]],["evening",QUESTIONS[1]],["weekly",QUESTIONS[2]]].map(([type,prompt])=>[type,buildPrompt(context,prompt,settings).prompt])),[context,settings]);
  const suggestions = useMemo(() => identifySuggestions(response), [response]);
  const promptOptions = [...new Set([...(settings.favoritePrompts || []), ...QUESTIONS, ...traces.map(item => item.question)])].slice(0, 12);
  if (!settings.enabled) return <div style={S.screen}><Card><CardContent className="p-5 text-sm text-muted-foreground">AI Workspace is disabled in Settings.</CardContent></Card></div>;

  async function copy() { await navigator.clipboard.writeText(result.prompt); recordPromptTrace(result.preview, question); setTraces(readPromptTraces()); setCopied(true); setTimeout(() => setCopied(false), 2000); }
  function toggleFavorite() { const favorites = settings.favoritePrompts || []; const next = favorites.includes(question) ? favorites.filter(item => item !== question) : [question, ...favorites].slice(0, 8); const saved = writeAiSettings({ ...settings, favoritePrompts: next }); setSettings(saved); }
  function openWorkflow(item) { const nav = workflowNavigation(item); if (nav) onNavigate(nav); }

  return <div style={S.screen} className="space-y-4 overflow-x-hidden">
    <div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-muted-foreground"><Bot className="h-4 w-4" />AI Workspace</div><h1 className="mt-1 text-2xl font-extrabold">Ask FamilyOS</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Review, copy, and turn recommendations into prefilled forms. Nothing is transmitted or saved without your confirmation.</p></div>
    <BriefScheduler promptByType={scheduledPrompts} initialType={initialView?.briefType}/>
    <Card><CardContent className="space-y-3 p-4"><div className="flex items-center justify-between gap-2"><label htmlFor="ai-question" className="text-sm font-bold">Question</label><Button type="button" size="xs" variant="ghost" aria-label="Favorite current prompt" onClick={toggleFavorite}><Heart className={(settings.favoritePrompts || []).includes(question) ? "fill-current" : ""} />{(settings.favoritePrompts || []).includes(question) ? "Favorited" : "Favorite"}</Button></div><Input id="ai-question" value={question} onChange={event => setQuestion(event.target.value)} /><div className="flex max-h-28 flex-wrap gap-2 overflow-y-auto" aria-label="Favorite and recent prompts">{promptOptions.map(item => <Button key={item} type="button" size="xs" variant={(settings.favoritePrompts || []).includes(item) ? "default" : "secondary"} onClick={() => setQuestion(item)}>{item}</Button>)}</div></CardContent></Card>
    {settings.promptPreview && <Card><CardContent className="space-y-3 p-4"><SectionHeader title="Prompt Preview" tone="purple" /><div className="grid grid-cols-1 gap-2 text-xs sm:grid-cols-2"><div><b>Included modules</b><div className="break-words">{result.preview.includedModules.join(", ") || "None"}</div></div><div><b>Estimated size</b><div>~{result.preview.estimatedTokens} tokens</div></div><div><b>Prompt version</b><div>{result.preview.promptVersion}</div></div><div><b>Context / privacy</b><div>{result.preview.contextVersion} / {result.preview.privacyFilterVersion}</div></div></div><ExpandableSection title="Privacy and exclusions" storageKey="ai-preview-privacy" defaultOpen={false}><div className="flex items-start gap-2 rounded-lg border border-border bg-secondary p-3 text-xs leading-5"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><span>{result.preview.privacyNotes.join(" · ")} · {result.preview.excludedSections.length ? `${result.preview.excludedSections.length} sections excluded` : "No optional sections excluded"}</span></div></ExpandableSection><ExpandableSection title="Full generated prompt" storageKey="ai-preview-full" defaultOpen={false}><textarea readOnly value={result.prompt} aria-label="Generated FamilyOS prompt" className="min-h-64 w-full rounded-md border border-border bg-secondary p-3 text-xs leading-5" /></ExpandableSection><Button type="button" className="w-full" onClick={copy}>{copied ? <Check /> : <Clipboard />}{copied ? "Copied" : "Copy Prompt"}</Button></CardContent></Card>}
    <Card><CardContent className="space-y-3 p-4"><SectionHeader title="AI Response Review" tone="neutral" /><p className="text-xs leading-5 text-muted-foreground">Paste a response using labels such as Task:, Calendar:, Pool:, Life List:, or Finance:. Review opens the owning form with suggested values. You still choose whether to save.</p><textarea value={response} onChange={event => setResponse(event.target.value)} aria-label="AI response to review" placeholder="Paste AI output here" className="min-h-36 w-full rounded-md border border-border bg-secondary p-3 text-sm" />{suggestions.map(item => <div key={item.id} className="flex flex-col gap-3 rounded-lg border border-border p-3 sm:flex-row sm:items-start"><Eye className="mt-1 h-4 w-4 shrink-0 text-primary" /><div className="min-w-0 flex-1"><div className="text-xs font-bold text-muted-foreground">{item.label}</div><div className="break-words text-sm">{item.text}</div></div>{item.type === "calendar" ? <Button asChild size="xs" variant="secondary"><a href={googleCalendarUrl(item)} target="_blank" rel="noreferrer">Review in Calendar<ExternalLink /></a></Button> : <Button size="xs" variant="secondary" onClick={() => openWorkflow(item)}>Review prefilled form</Button>}</div>)}</CardContent></Card>
    <Card><CardContent className="p-4"><SectionHeader title="Recent Prompts" count={traces.length} tone="neutral" />{traces.length ? traces.map(item => <button type="button" onClick={() => setQuestion(item.question)} key={item.timestamp} className="block min-h-11 w-full border-b border-border py-2 text-left text-xs last:border-0"><span className="block font-semibold">{item.question}</span><span className="block break-words text-muted-foreground">{new Date(item.timestamp).toLocaleString()} · {item.modulesIncluded.join(", ")} · ~{item.estimatedTokenCount} tokens</span></button>) : <p className="text-sm text-muted-foreground">No prompts copied on this device.</p>}</CardContent></Card>
  </div>;
}
