import { useEffect, useMemo, useState } from "react";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { Checkbox } from "../../components/ui/checkbox";
import { Input } from "../../components/ui/input";
import { Label } from "../../components/ui/label";
import { SectionHeader } from "../../components/ui/section-header";
import { Switch } from "../../components/ui/switch";
import { useTable } from "../../hooks/useTable";
import { BRIEF_TYPES, DEFAULT_BRIEF_SCHEDULES, briefLabel, dueBriefs, scheduledPeriodKey } from "../../services/briefScheduling";

const DAY_LABELS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
export function BriefScheduler({promptByType={},initialType}){
 const schedules=useTable("brief_schedules","created_at",true),history=useTable("brief_generation_history","generated_at");
 const [draft,setDraft]=useState(DEFAULT_BRIEF_SCHEDULES),[message,setMessage]=useState("");
 useEffect(()=>{if(!schedules.data.length)return;setDraft(previous=>({...previous,...Object.fromEntries(schedules.data.map(row=>[row.brief_type,{enabled:row.enabled,time:String(row.preferred_time).slice(0,5),days:row.active_days||[]}]))}));},[schedules.data]);
 const due=useMemo(()=>dueBriefs(draft,history.data),[draft,history.data]);
 async function save(){for(const type of BRIEF_TYPES){const existing=schedules.data.find(row=>row.brief_type===type),row={brief_type:type,enabled:draft[type].enabled,preferred_time:draft[type].time,active_days:draft[type].days,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"America/New_York"};if(existing)await schedules.update(existing.id,row);else await schedules.insert(row);}setMessage("Brief schedule saved for this household member.");}
 async function generate(type,triggerType="manual"){const prompt=promptByType[type]||"";if(prompt.length<80){setMessage(`${briefLabel(type)} was not prepared because current context is too limited.`);return;}const period=scheduledPeriodKey(type);const existing=history.data.find(row=>row.brief_type===type&&row.period_key===period&&row.trigger_type==="scheduled"&&row.status==="generated");if(triggerType==="scheduled"&&existing){setMessage(`${briefLabel(type)} was already prepared for this period.`);return;}await history.insert({brief_type:type,period_key:period,trigger_type:triggerType,status:"generated",generated_at:new Date().toISOString(),context_summary:{prompt_length:prompt.length},prompt_text:prompt});setMessage(`${briefLabel(type)} prepared. Review the proposal below; no FamilyOS records changed.`);}
 useEffect(()=>{if(initialType&&BRIEF_TYPES.includes(initialType))setMessage(`${briefLabel(initialType)} is due. Prepare it when you are ready.`);},[initialType]);
 return <section aria-labelledby="brief-scheduling-title" className="space-y-3"><SectionHeader title="Brief Scheduling" count={due.length} tone="purple"/><p id="brief-scheduling-title" className="text-xs leading-5 text-muted-foreground">FamilyOS prepares due briefs when you open the authenticated app. Background delivery is not configured. Briefs are proposals and never change records automatically.</p>{message&&<div role="status" className="rounded-lg border border-primary/40 bg-primary/10 p-3 text-sm">{message}</div>}{BRIEF_TYPES.map(type=>{const latest=history.data.find(row=>row.brief_type===type);return <Card key={type} className={due.includes(type)||initialType===type?"border-amber-500":""}><CardContent className="space-y-3 p-4"><div className="flex items-center justify-between gap-3"><div><div className="font-bold">{briefLabel(type)}</div><div className="text-xs text-muted-foreground">{latest?`Previously generated ${new Date(latest.generated_at).toLocaleString()}`:"Not generated yet"}</div></div><Switch aria-label={`Enable ${briefLabel(type)}`} checked={draft[type].enabled} onCheckedChange={enabled=>setDraft(p=>({...p,[type]:{...p[type],enabled}}))}/></div><div><Label htmlFor={`brief-time-${type}`}>Preferred time</Label><Input id={`brief-time-${type}`} type="time" value={draft[type].time} onChange={e=>setDraft(p=>({...p,[type]:{...p[type],time:e.target.value}}))}/></div><fieldset><legend className="mb-2 text-xs font-bold">Applicable days</legend><div className="flex flex-wrap gap-2">{DAY_LABELS.map((label,day)=><label key={label} className="flex min-h-11 items-center gap-1 rounded-md border border-border px-2 text-xs"><Checkbox checked={draft[type].days.includes(day)} onCheckedChange={()=>setDraft(p=>({...p,[type]:{...p[type],days:p[type].days.includes(day)?p[type].days.filter(x=>x!==day):[...p[type].days,day]}}))}/>{label}</label>)}</div></fieldset><div className="flex gap-2"><Button type="button" size="xs" onClick={()=>generate(type,due.includes(type)?"scheduled":"manual")}>{due.includes(type)?"Prepare due brief":"Generate now"}</Button>{latest&&<Button type="button" size="xs" variant="secondary" onClick={()=>generate(type,"refresh")}>Refresh</Button>}</div>{latest&&<details><summary className="cursor-pointer text-xs font-semibold">View previously generated brief prompt</summary><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap rounded-md bg-secondary p-3 text-xs">{latest.prompt_text}</pre></details>}</CardContent></Card>})}<Button type="button" className="w-full" onClick={save} disabled={schedules.loading}>Save brief schedule</Button></section>;
}
