const FIELD_BY_NAME=[[/acid/i,"muriatic_acid_oz"],[/salt/i,"salt_lbs"],[/cya|stabilizer/i,"cya_oz"],[/chlorine/i,"liquid_chlorine_oz"]];
export function treatmentPrefill(recommendations, latest, now=new Date()) {
  const chemical=(recommendations||[]).filter(item=>item.category==="Chemical"&&item.amount); const form={date:now.toISOString().slice(0,10),time:now.toTimeString().slice(0,5),related_reading_id:latest?.id||null,reason:"FamilyOS treatment recommendation",notes:chemical.map(x=>x.action).join("; ")};
  chemical.forEach(rec=>{const match=String(rec.amount).match(/([\d.]+)\s*([a-zA-Z%]+)/);if(!match)return;const field=FIELD_BY_NAME.find(([pattern])=>pattern.test(`${rec.action} ${rec.amount}`))?.[1];if(field)form[field]=Number(match[1]);if(!form.treatment)form.treatment=rec.action;if(!form.amount){form.amount=Number(match[1]);form.unit=match[2];}}); return form;
}
export function buildPoolChatPrompt({profile={},equipment=[],latest=null,readings=[],treatments=[],recommendations=[],trends=[]}={}) {
  const clean=value=>value===null||value===undefined||value===""?"Not available":value;
  const lines=["Review this FamilyOS pool-care context. Do not assume missing values.","",`Pool: ${clean(profile.volume_gallons)} gallons; surface ${clean(profile.surface_type)}; saltwater ${profile.saltwater?"yes":"no"}; sanitizer ${clean(profile.sanitizer_type)}.`,`Equipment: ${equipment.map(x=>`${x.name||x.type}${x.brand?` (${x.brand} ${x.model||""})`:""}`).join(", ")||"Not available"}.`,`Current SWG: ${clean(latest?.swg_setting??profile.swg_output_percent)}%.`,`Latest readings: ${latest?`pH ${clean(latest.ph)}, FC ${clean(latest.free_chlorine)}, CC ${clean(latest.cc)}, TA ${clean(latest.alkalinity)}, CYA ${clean(latest.cya)}, salt ${clean(latest.salt)}, calcium ${clean(latest.calcium_hardness)}, temperature ${clean(latest.water_temp)} F`:"Not available"}.`,`Recent tests: ${readings.slice(0,5).map(x=>`${x.date}: pH ${clean(x.ph)}, FC ${clean(x.free_chlorine)}, salt ${clean(x.salt)}`).join("; ")||"Not available"}.`,`Recent additions: ${treatments.slice(0,5).map(x=>`${x.date}: ${x.treatment||x.notes||"treatment logged"}`).join("; ")||"None logged"}.`,`FamilyOS recommendation: ${recommendations.map(x=>`${x.action}${x.amount?` (${x.amount})`:""}`).join("; ")||"No current treatment recommendation"}.`,`Trends: ${trends.map(x=>`${x.name}: ${x.detail||x.direction||"stable/unknown"}`).join("; ")||"Not available"}.`,`Existing weather/use context: ${clean(latest?.recent_weather_notes)}; heavy use ${latest?.recent_heavy_usage?"yes":"no"}.`,"","Please: (1) review readings and trends, (2) validate or challenge the FamilyOS recommendation, (3) identify safety concerns, (4) recommend specific next steps, (5) state when to retest, (6) state whether swimming appears appropriate based only on supplied readings, and (7) identify missing information.","Safety: AI analysis supplements, and never overrides, validated pool testing, product labels, or professional guidance."];
  return lines.join("\n");
}
