import { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, FileText, Heart, Home, ListTodo, Waves } from "lucide-react";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card,CardContent } from "../../components/ui/card";
import { EmptyStatePanel } from "../../components/ui/empty-state";
import { Input } from "../../components/ui/input";
import { Select } from "../../components/ui/select";
import { Skeleton } from "../../components/ui/skeleton";
import { useHousehold } from "../../context/HouseholdContext";
import { useTable } from "../../hooks/useTable";
import { normalizeTimeline,timelineGroup } from "../../services/timeline";
import { S } from "../../theme";

const iconFor=type=>({task:ListTodo,calendar:CalendarDays,habit:CheckCircle2,pool:Waves,home:Home,maintenance:Home,note:FileText,relationship:Heart}[type]||Clock3);
const GROUPS=["Today","Yesterday","Earlier","Upcoming"];
export function HouseholdTimeline({calendarEvents=[],onNavigate}){
  const household=useHousehold();const [query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[limit,setLimit]=useState(60);
  const tasks=useTable("tasks","updated_at"),habits=useTable("habit_completions","completed_at"),readings=useTable("pool_readings","logged_at"),treatments=useTable("pool_treatments","logged_at"),poolMaintenance=useTable("pool_maintenance","date"),assets=useTable("home_assets","updated_at"),homeHistory=useTable("home_asset_history","completed_at"),notes=useTable("notes","created_at"),activity=useTable("household_activity","occurred_at"),relationshipActivities=useTable("relationship_activities","occurred_at"),relationships=useTable("relationships","name",true);
  const loading=[tasks,habits,readings,treatments,poolMaintenance,assets,homeHistory,notes,activity,relationshipActivities,relationships].some(table=>table.loading);
  const relationshipNames=useMemo(()=>Object.fromEntries(relationships.data.map(item=>[item.id,item.name])),[relationships.data]);
  const items=useMemo(()=>normalizeTimeline({tasks:tasks.data,calendar:calendarEvents,habitCompletions:habits.data,poolReadings:readings.data,poolTreatments:treatments.data,poolMaintenance:poolMaintenance.data,homeAssets:assets.data,homeHistory:homeHistory.data,notes:notes.data,activity:activity.data,relationshipActivities:relationshipActivities.data},{householdId:household.householdId,relationshipNames,limit:200}).filter(item=>(filter==="all"||item.sourceType===filter)&&`${item.title} ${item.summary}`.toLowerCase().includes(query.toLowerCase())).slice(0,limit),[activity.data,assets.data,calendarEvents,filter,habits.data,homeHistory.data,household.householdId,limit,notes.data,poolMaintenance.data,query,readings.data,relationshipActivities.data,relationshipNames,tasks.data,treatments.data]);
  return <main style={S.screen} className="space-y-5 overflow-x-hidden" aria-label="Household Timeline"><div><div className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Unified Context</div><h1 className="mt-1 text-2xl font-extrabold">Household Timeline</h1><p className="mt-2 text-sm text-muted-foreground">A chronological, household-scoped record. Shopping is intentionally excluded.</p></div><div className="grid gap-2 sm:grid-cols-[1fr_180px]"><Input aria-label="Search timeline" placeholder="Search timeline" value={query} onChange={event=>setQuery(event.target.value)}/><Select aria-label="Filter timeline by module" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All modules</option>{["relationship","task","calendar","habit","pool","home","maintenance","note"].map(value=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</Select></div>{loading?<div className="space-y-2"><Skeleton className="h-24"/><Skeleton className="h-24"/></div>:items.length?GROUPS.map(group=>{const groupItems=items.filter(item=>timelineGroup(item)===group);return groupItems.length?<section key={group} aria-labelledby={`timeline-${group}`}><h2 id={`timeline-${group}`} className="mb-2 text-sm font-extrabold uppercase tracking-wide text-muted-foreground">{group}</h2><div className="space-y-2">{groupItems.map(item=>{const Icon=iconFor(item.sourceType);return <Card key={item.id}><CardContent className="flex gap-3 p-4"><Icon className="mt-0.5 h-5 w-5 shrink-0 text-primary" aria-hidden="true"/><button type="button" className="min-w-0 flex-1 text-left" onClick={()=>item.deepLink&&onNavigate(item.deepLink)}><span className="flex flex-wrap items-center gap-2"><span className="font-bold">{item.title}</span><Badge variant="blue">{item.sourceType}</Badge></span>{item.summary&&<span className="mt-1 block text-sm text-muted-foreground">{item.summary}</span>}<span className="mt-2 block text-xs text-muted-foreground">{item.effectiveDate||"Date unavailable"} · {item.status}</span></button></CardContent></Card>})}</div></section>:null}):<Card><EmptyStatePanel title="No timeline activity" detail="Try a different filter or add a household record."/></Card>}{items.length>=limit&&<Button type="button" variant="secondary" className="w-full" onClick={()=>setLimit(value=>value+60)}>Load more</Button>}</main>;
}
